<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add' => 'Toevoegen',
    'Are you sure you want to send reminder to this business?' => 'Weet je zeker dat je een herinnering naar dit bedrijf wilt sturen?',
    'Authenticate Virtual MFA' => 'Virtuele MFA authenticeren',
    'Authentication Code 1' => 'Authenticatiecode 1',
    'Authentication Code 2' => 'Authenticatiecode 2',
    'Business ID' => 'Bedrijfs-ID',
    'Businesses' => 'Ondernemingen',
    'Cancel and return to the login page' => 'Annuleer en ga terug naar de inlogpagina',
    'Credits' => 'credits',
    'First' => 'Eerste',
    'Go to view' => 'Ga naar weergave',
    'Identity Bank' => 'Identity Bank',
    'Identity Bank payment reminder.' => 'Identity Bank betalingsherinnering.',
    'Invalid code' => 'Ongeldige code',
    'Invoices' => 'Facturen',
    'Last' => 'Laatste',
    'Login' => 'Aanmelding',
    'Login Page' => 'Loginpagina',
    'MFA Code' => 'MFA Code',
    'Multi-factor Authentication' => 'Multi-factor Authenticatie',
    'OR ' => 'OF',
    'Or sign in as a different user' => 'Of meld u aan als een andere gebruiker',
    'Package' => 'Pakket',
    'Payments' => 'betalingen',
    'Please enter an MFA code to complete sign-in.' => 'Voer een MFA-code in om de aanmelding te voltooien.',
    'Please fill out the following fields to login to the Identity Bank' => 'Gelieve de volgende velden in te vullen om in te loggen op de Identity Bank',
    'Provide two consecutive authentication codes to verify.' => 'Geef twee opeenvolgende authenticatiecodes op om te verifiëren.',
    'Provide two consecutive authentication codes.' => 'Zorg voor twee opeenvolgende authenticatiecodes.',
    'Save' => 'Opslaan',
    'Submit' => 'Indienen',
    'User profile' => 'Gebruikersprofiel',
    'Your email was sent successfully.' => 'Uw e-mail werd met succes verzonden.',
    'Your email wasn\'t sent successfully.' => 'Uw e-mail is niet succesvol verzonden.',
];
