<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add' => 'Dodaj',
    'Are you sure you want to send reminder to this business?' => 'Czy na pewno chcesz wysłać przypomnienie do tej firmy?',
    'Authenticate Virtual MFA' => 'Uwierzytelniające wirtualne MFA',
    'Authentication Code 1' => 'Kod uwierzytelniający 1',
    'Authentication Code 2' => 'Kod uwierzytelniający 2',
    'Business ID' => 'ID Firmy',
    'Businesses' => 'Firmy',
    'Cancel and return to the login page' => 'Anuluj i wróć do strony logowania',
    'Credits' => 'Kredyty',
    'First' => 'Pierwsza',
    'Go to view' => 'Idź do widoku',
    'Identity Bank' => 'Identity Bank',
    'Identity Bank payment reminder.' => 'Przypomnienie o płatności z Identity Banku',
    'Invalid code' => 'Nieprawidłowy kod',
    'Invoices' => 'Faktury',
    'Last' => 'Ostatnia',
    'Login' => 'Login',
    'Login Page' => 'Strona logowania',
    'MFA Code' => 'Kod MFA',
    'Multi-factor Authentication' => 'Uwierzytelnianie wielopoziomowe',
    'OR ' => 'LUB',
    'Or sign in as a different user' => 'Lub zaloguj się jako inny użytkownik',
    'Package' => 'Pakiet',
    'Payments' => 'Płatności',
    'Please enter an MFA code to complete sign-in.' => 'Proszę wpisać kod MFA, aby dokończyć logowanie.',
    'Please fill out the following fields to login to the Identity Bank' => 'Wypełnij następujące pola, aby zalogować się do Identity Banku',
    'Provide two consecutive authentication codes to verify.' => 'Podaj dwa kolejne kody uwierzytelniające do weryfikacji.',
    'Provide two consecutive authentication codes.' => 'Podaj dwa kolejne kody uwierzytelniające.',
    'Save' => 'Zapisz',
    'Submit' => 'Wyślij',
    'User profile' => 'Profil użytkownika',
    'Your email was sent successfully.' => 'Twój e-mail został wysłany pomyślnie.',
    'Your email wasn\'t sent successfully.' => 'Twój e-mail nie został wysłany pomyślnie.',
];
