<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add' => '',
    'Are you sure you want to send reminder to this business?' => '',
    'Authenticate Virtual MFA' => '',
    'Authentication Code 1' => '',
    'Authentication Code 2' => '',
    'Business ID' => '',
    'Businesses' => '',
    'Cancel and return to the login page' => '',
    'Credits' => '',
    'First' => '',
    'Go to view' => '',
    'Identity Bank' => '',
    'Identity Bank payment reminder.' => '',
    'Invalid code' => '',
    'Invoices' => '',
    'Last' => '',
    'Login' => '',
    'Login Page' => '',
    'MFA Code' => '',
    'Multi-factor Authentication' => '',
    'OR ' => '',
    'Or sign in as a different user' => '',
    'Package' => '',
    'Payments' => '',
    'Please enter an MFA code to complete sign-in.' => '',
    'Please fill out the following fields to login to the Identity Bank' => '',
    'Provide two consecutive authentication codes to verify.' => '',
    'Provide two consecutive authentication codes.' => '',
    'Save' => '',
    'Submit' => '',
    'User profile' => '',
    'Your email was sent successfully.' => '',
    'Your email wasn\'t sent successfully.' => '',
];
